### ISSUE TITLE
Code for the UCI experiments

### ISSUE THREAD

**Issue by tvatter** [logchan/dde#1]
Hey,

Really nice paper, I took a lot of interest!

Quick question: do you have the code that you used for Table 2 to reproduce your state-of-the-art results?

Thanks a lot!

Thibault

**Comment by logchan** [comment]
Hi Thibault,

Thanks for your interest. We found it and we'll update the repo soon.

Geng

**Comment by tvatter** [comment]
Thanks a lot for your answer. If you close this issue whenever you update the repo, I'll be notified automatically :)

Best,
Thibault
